# Generated by Django 4.2.6 on 2023-11-10 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
