# Generated by Django 4.2.6 on 2023-11-10 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_customuser'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('isbn', 'title')},
        ),
    ]
